devbhuwan:
  cloud:
    service:
      cros-allow-orgin: false

server:
  port: 8788

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/testdb
    username: sa
    password: sa
  activiti:
    process-definition-location-prefix: classpath:workflows/
    deployment-name: order-workflow